# Generated by Django 2.2.10 on 2020-03-04 04:08

from django.db import migrations, models
import django.db.models.deletion
import items.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('730251ac-13f3-415f-b38b-8180bfec7d48'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5f8f7130-fc80-4cf1-a501-0c856163e6b2'), editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[(items.models.TransactionStatus('Processing'), 'Processing'), (items.models.TransactionStatus('Completed'), 'Completed'), (items.models.TransactionStatus('Error'), 'Error')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, choices=[(items.models.TransactionLocation('Origination Bank'), 'Origination Bank'), (items.models.TransactionLocation('Routable'), 'Routable'), (items.models.TransactionLocation('Destination Bank'), 'Destination Bank')], max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='items.Item')),
            ],
        ),
    ]
