# Generated by Django 2.2.10 on 2020-03-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200303_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
