# Generated by Django 2.2.10 on 2020-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200304_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.CharField(choices=[('originator_bank', 'Originator Bank'), ('routable', 'Routable'), ('destination_bank', 'Destination Bank')], default='originator_bank', max_length=20),
        ),
    ]
