# Generated by Django 2.2.10 on 2020-03-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200306_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('processing', 'First Time Processing'), ('correcting', 'Any Unfinished Correction'), ('error', 'Error'), ('resolved', 'Positive Finish State')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether or not this Transaction is currently the active Transaction for its Item'),
        ),
    ]
